FROM python:3.6.5-slim-jessie
COPY ./src /server
WORKDIR /server
EXPOSE 8767
RUN apt-get update && apt-get install -y build-essential  &&  pip install -r requirements.txt
CMD ["python", "subscriber.py"]
 
