FROM python:3.5.5-slim-jessie
COPY ./src /server
WORKDIR /server
EXPOSE 8765
RUN apt-get update && apt-get install -y build-essential  &&  pip install -r requirements.txt
CMD ["python", "publisher.py"]
 
